// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function db(ctx) {
  return createClient(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "List properties",
  description: "List properties the signed-in user can access in RentFlow.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db(ctx).from("properties").select("id, name, address, total_units, status, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tenants.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function db2(ctx) {
  return createClient2(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tenants_default = defineTool2({
  name: "list_tenants",
  title: "List tenants",
  description: "List tenants the signed-in user can access, optionally filtered by property.",
  inputSchema: {
    property_id: z2.string().uuid().optional().describe("Filter tenants by property id."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db2(ctx).from("tenants").select("id, first_name, last_name, email, phone, property_id, unit_number, status, rent_amount").order("created_at", { ascending: false }).limit(limit);
    if (property_id) q = q.eq("property_id", property_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tenants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function db3(ctx) {
  return createClient3(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool3({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices, optionally filtered by tenant or status (pending, paid, overdue).",
  inputSchema: {
    tenant_id: z3.string().uuid().optional(),
    status: z3.enum(["pending", "paid", "overdue", "partial"]).optional(),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db3(ctx).from("invoices").select("id, tenant_id, amount, amount_paid, status, due_date, month, created_at").order("due_date", { ascending: false }).limit(limit);
    if (tenant_id) q = q.eq("tenant_id", tenant_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function db4(ctx) {
  return createClient4(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payments_default = defineTool4({
  name: "list_payments",
  title: "List payments",
  description: "List recorded rent payments, optionally filtered by tenant.",
  inputSchema: {
    tenant_id: z4.string().uuid().optional(),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db4(ctx).from("payments").select("id, tenant_id, amount, payment_method, status, payment_date, notes").order("payment_date", { ascending: false }).limit(limit);
    if (tenant_id) q = q.eq("tenant_id", tenant_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { payments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-maintenance.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function db5(ctx) {
  return createClient5(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_maintenance_default = defineTool5({
  name: "list_maintenance_requests",
  title: "List maintenance requests",
  description: "List maintenance requests, optionally filtered by status.",
  inputSchema: {
    status: z5.enum(["open", "in_progress", "resolved", "closed"]).optional(),
    limit: z5.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db5(ctx).from("maintenance_requests").select("id, tenant_id, property_id, title, description, status, priority, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "elebtxleydldblwcidmq";
var mcp_default = defineMcp({
  name: "rentflow-mcp",
  title: "RentFlow MCP",
  version: "0.1.0",
  instructions: "Read-only tools for RentFlow property management. Use these to query properties, tenants, invoices, payments, and maintenance requests for the signed-in user. Results respect the user's role-based access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, list_tenants_default, list_invoices_default, list_payments_default, list_maintenance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
